version: '3'
services:
  nginx:
    container_name: "nginx"
    build:
      context: ./docker/nginx
    depends_on:
      - app
    ports:
      - 80:80
    volumes:
      - ./:/src

  app:
    container_name: "app"
    build:
      context: ./docker/php
    depends_on:
      - mysql
    volumes:
      - ./:/src
      - /src/node_modules
      - /src/vendor
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini

  mysql:
    platform: linux/x86_64
    image: mysql:8.0.33
    command: --max_allowed_packet=32505856
    container_name: "mysql"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: time_manager_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'

    ports:
      - 3306:3306

  phpmyadmin:
   image: phpmyadmin
   ports:
       - 8080:80
   environment:
       - PMA_HOSTS=mysql
       - PMA_USER=admin
       - PMA_PASSWORD=password
   depends_on:
      - mysql 

  redis:
    image: redis:alpine
    container_name: "redis"
    ports:
      - 16379:6379